// src/components/sleeping-beauty-svelte/NarrationText.svelte
<script>
import { onMount, onDestroy, createEventDispatcher } from 'svelte';
import Typed from 'typed.js';

export let text;
export let skipTyping;

const dispatch = createEventDispatcher();
let elementRef;
let typed = null;
let finalText = '';
let displayText = '';
let isComplete = false;

const handleTypingComplete = () => {
  if (typed?.cursor) {
    typed.cursor.style.display = 'none';
  }
  
  finalText = text;
  displayText = text;
  isComplete = true;
  
  // Call onComplete in next frame to ensure state is settled
  requestAnimationFrame(() => {
    dispatch('complete');
  });
};

const handleSkip = (e) => {
  if (isComplete || !typed) return;

  e.stopPropagation();
  
  // Cleanup typed instance first
  if (typed) {
    typed.destroy();
    typed = null;
  }
  
  // Then complete
  handleTypingComplete();
};

onMount(() => {
  // If already complete, maintain text visibility
  if (isComplete) {
    displayText = finalText;
    return;
  }

  // Handle skip request
  if (skipTyping) {
    finalText = text;
    displayText = text;
    isComplete = true;
    dispatch('complete');
    return;
  }

  // Start new typing animation
  if (elementRef && text) {
    typed = new Typed(elementRef, {
      strings: [text],
      typeSpeed: 35,
      showCursor: true,
      cursorChar: '▎',
      loop: false,
      fadeOut: false,
      backspace: 0,
      onComplete: handleTypingComplete,
      startDelay: 400,
      contentType: 'html',
    });

    // Add skip handler
    document.addEventListener('click', handleSkip);
  }

  return () => {
    if (typed) {
      typed.destroy();
      typed = null;
    }
    document.removeEventListener('click', handleSkip);
  };
});
</script>

<div class="relative px-4 pb-6 md:pb-8" 
  in:fade={{duration: 500, y: 20}}>
  <div 
    bind:this={elementRef}
    class="text-lg md:text-xl text-white/90 font-medium leading-relaxed tracking-wide"
    style="min-height: 6rem; text-shadow: 0 2px 4px rgba(0,0,0,0.5); max-width: 70ch; margin: 0 auto;"
  >
    {@html displayText}
  </div>
  
  {#if !isComplete && !skipTyping}
    <div
      class="absolute bottom-0 right-0 text-sm text-white/50 italic"
      in:fade={{delay: 1000}}
    >
      Click anywhere to skip
    </div>
  {/if}
</div>

<style>
  .fade-enter {
    opacity: 0;
    transform: translateY(20px);
  }
  .fade-enter-active {
    transition: opacity 500ms, transform 500ms;
  }
  .fade-enter-to {
    opacity: 1;
    transform: translateY(0);
  }
</style>

// src/components/sleeping-beauty/NarrationText.jsx
import React, { useEffect, useRef, useCallback, useState, useLayoutEffect } from 'react';
import Typed from 'typed.js';
import { motion } from 'framer-motion';

function NarrationText({ text, onComplete, skipTyping, setSkipTyping }) {
  const elementRef = useRef(null);
  const typedRef = useRef(null);
  const finalTextRef = useRef('');
  const [displayText, setDisplayText] = useState('');
  const [isComplete, setIsComplete] = useState(false);
  const onCompleteRef = useRef(onComplete);
  
  // Update onComplete ref when prop changes
  useEffect(() => {
    onCompleteRef.current = onComplete;
  }, [onComplete]);

  // Ensure display text stays visible
  useLayoutEffect(() => {
    if (isComplete && finalTextRef.current && !displayText) {
      setDisplayText(finalTextRef.current);
    }
  }, [displayText, isComplete]);

  const handleTypingComplete = useCallback((self) => {
    if (self?.cursor) {
      self.cursor.style.display = 'none';
    }
    
    finalTextRef.current = text;
    setDisplayText(text);
    setIsComplete(true);
    
    // Call onComplete in next frame to ensure state is settled
    requestAnimationFrame(() => {
      onCompleteRef.current?.();
    });
  }, [text]);

  const handleSkip = useCallback((e) => {
    if (isComplete || !typedRef.current) return;

    e.stopPropagation();
    
    // Cleanup typed instance first
    if (typedRef.current) {
      typedRef.current.destroy();
      typedRef.current = null;
    }
    
    // Then complete
    handleTypingComplete();
  }, [handleTypingComplete, isComplete]);

  useLayoutEffect(() => {
    // If already complete, maintain text visibility
    if (isComplete) {
      setDisplayText(finalTextRef.current);
      return;
    }

    // Handle skip request
    if (skipTyping) {
      finalTextRef.current = text;
      setDisplayText(text);
      setIsComplete(true);
      onCompleteRef.current?.();
      return;
    }

    // Start new typing animation
    if (elementRef.current && text) {
      const typed = new Typed(elementRef.current, {
        strings: [text],
        typeSpeed: 35,
        showCursor: true,
        cursorChar: '▎',
        loop: false,
        fadeOut: false,
        backspace: 0,
        onComplete: handleTypingComplete,
        startDelay: 400,
        contentType: 'html',
      });

      typedRef.current = typed;

      // Add skip handler
      document.addEventListener('click', handleSkip);
    }

    // Cleanup
    return () => {
      if (typedRef.current) {
        typedRef.current.destroy();
        typedRef.current = null;
      }
      document.removeEventListener('click', handleSkip);
    };
  }, [text, skipTyping, handleTypingComplete, handleSkip, isComplete]);

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className="relative px-4 pb-6 md:pb-8"
    >
      <div 
        ref={elementRef}
        className="text-lg md:text-xl text-white/90 font-medium leading-relaxed tracking-wide"
        style={{ 
          minHeight: '6rem',
          textShadow: '0 2px 4px rgba(0,0,0,0.5)',
          maxWidth: '70ch',
          margin: '0 auto',
        }}
        dangerouslySetInnerHTML={{ __html: displayText }}
      />
      {!isComplete && !skipTyping && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 1 }}
          className="absolute bottom-0 right-0 text-sm text-white/50 italic"
        >
          Click anywhere to skip
        </motion.div>
      )}
    </motion.div>
  );
}

export default NarrationText;
